const labels={
  'get_recent_measurements':['계측 요약','신고 전 계측 창의 값과 범위'],
  'get_signal_definitions':['신호 정의','1·2차측 센서와 단위'],
  'get_prior_incidents':['이전 신고','사건 이전 공개 기록'],
  'get_maintenance_timeline':['이력 타임라인','사건 이전 정비·교란 기록'],
  'get_temporal_episodes':['시간별 편차 구간','연속 짝지은 온도·설정값'],
  'query_measurement_window':['시간 창 조회','지정 구간의 짝지은 계측'],
  'finish_investigation':['조사 종료 신호','최종 생성 단계로 이동']
};
const checkLabels={'C-room-impact':'고객 측 영향 범위 확인','C-secondary-flow':'2차측 난방 유량 측정','C-controls':'제어기 설정·경보 검토'};
const limitLabels={'L-no-room-evidence':'공급온도가 설정값을 따른다고 실내로 열이 전달됐다고 말할 수 없습니다.','L-no-normal-range':'열량·유량의 정상 운전 범위가 제공되지 않았습니다.','L-primary-flow':'1차측 계량 유량은 2차측 또는 고객 회로 유량이 아닙니다.'};
const state={case:'29',data:null,selected:0};
const $=sel=>document.querySelector(sel);
function el(name,cls,text){const node=document.createElement(name);if(cls)node.className=cls;if(text!==undefined)node.textContent=text;return node}
function displayValue(v){return typeof v==='object'?JSON.stringify(v,null,2):String(v??'—')}
function factNode(fact){const article=el('article','fact');article.id=`fact-${fact.id}`;const head=el('div','fact-head');head.append(el('code','',fact.id),el('span','',fact.unit||'PUBLIC RECORD'));article.append(head,el('p','fact-text',fact.text));const dl=el('dl');[['원자료 ID',fact.source_id],['원본 필드',fact.source_field],['시각 / 구간',fact.interval||'기록 필드'],['원본 값',displayValue(fact.value)]].forEach(([k,v])=>{dl.append(el('dt','',k),el('dd','',v))});article.append(dl);return article}
function render(){const d=state.data;const subtitle=state.case==='29'?'서브스테이션 17 · 신규 설비 사례 · 최초 고정 실행':'서브스테이션 21 · 개발 사례 · 비교 후 수정 실행';$('#incident-title').textContent=`PreDist / 장애 신고 ${state.case}`;$('#incident-subtitle').textContent=subtitle;$('#decision-time').textContent=d.decision_time.replace(' ',' / ');$('#case-meta').replaceChildren();const meta=$('#case-meta');[['결과',d.status==='reference_checked'?'형식·참조 검사 통과':d.status],['모델','Nemotron 3 Ultra'],['완료 방식',d.finish_reason],['도구 호출',`${d.tool_calls.length}회`],['실행 시간',`${d.wall_seconds.toFixed(1)}초`]].forEach(([k,v])=>{const row=el('div','meta-row');row.append(el('span','',k),el('strong','',v));meta.append(row)});
  $('#check-list').replaceChildren();d.checks.forEach((check,i)=>{const btn=el('button','check-item');btn.type='button';btn.setAttribute('aria-pressed',String(state.selected===i));btn.append(el('span','check-no',String(i+1).padStart(2,'0')),el('span','check-title',checkLabels[check.id]||check.text),el('span','check-arrow','↗'));const detail=el('small','',check.text);btn.querySelector('.check-title').append(detail);btn.addEventListener('click',()=>{state.selected=i;renderChecks()});$('#check-list').append(btn)});renderChecks();
  $('#tool-list').replaceChildren();d.tool_calls.forEach((tool,i)=>{const row=el('div','tool-item');row.append(el('span','tool-no',String(i+1).padStart(2,'0')));const body=el('div');body.append(el('strong','',labels[tool.name]?.[0]||tool.name),el('p','',labels[tool.name]?.[1]||''));if(Object.keys(tool.arguments).length)body.append(el('code','',Object.entries(tool.arguments).map(([k,v])=>`${k}: ${v}`).join(' / ')));row.append(body);$('#tool-list').append(row)});
  $('#limits').replaceChildren();d.limits.forEach(item=>$('#limits').append(el('li','',limitLabels[item.id]||item.text)));const review=$('#postrun-review-summary');review.hidden=!d.postrun_review;review.textContent=d.postrun_review?'사후 독립 AI 내용 검토에서 이 사건의 유량 점검 이유에 근거 연결 문제를 표시했습니다. 원래 모델 출력과 실행 trace는 수정하지 않았으며 현장 전문가 검증은 아닙니다. 아래 유량 점검을 선택해 세부 사항을 보세요.':'';const warn=$('#review-warning');warn.hidden=!d.budget_exhausted;warn.textContent=d.budget_exhausted?'개발 실행 경고: 6회 유효 조회 뒤 예산에 도달해 종료 신호 없이 최종 단계로 넘겼습니다. 충분한 조사를 모델이 선언한 것은 아닙니다.':'';$('#download-json').href=`assets/system2-${state.case}.json`;document.querySelectorAll('[data-case]').forEach(btn=>btn.setAttribute('aria-pressed',String(btn.dataset.case===state.case)))}
function renderChecks(){const d=state.data,check=d.checks[state.selected];document.querySelectorAll('.check-item').forEach((btn,i)=>btn.setAttribute('aria-pressed',String(i===state.selected)));$('#inspector-title').textContent=checkLabels[check.id]||check.text;$('#inspector-summary').textContent=check.rationale;const postrun=$('#postrun-check-review');const issues=d.postrun_review?.by_check?.[check.id]||[];postrun.hidden=issues.length===0;postrun.replaceChildren();if(issues.length){postrun.append(el('strong','','사후 독립 AI 내용 검토 · 원본 출력 보존'));issues.forEach(issue=>postrun.append(el('p','',issue)));postrun.append(el('small','','현장 전문가 검증이 아닌 AI 검토 결과입니다.'))}$('#fact-count').textContent=`${check.fact_ids.length} CITED FACTS`;const wrap=$('#facts');wrap.replaceChildren();check.fact_ids.forEach(id=>{const fact=d.facts[id];if(fact)wrap.append(factNode(fact))});}
async function loadCase(caseId){state.case=caseId;state.selected=0;try{const response=await fetch(`assets/system2-${caseId}.json`);if(!response.ok)throw new Error(`HTTP ${response.status}`);state.data=await response.json();render();history.replaceState(null,'',`${location.pathname}?case=${caseId}`)}catch(error){$('#check-list').textContent='공개 실행 데이터를 읽지 못했습니다. 정적 웹 서버로 이 페이지를 열어 주세요.';$('#inspector-summary').textContent=String(error)}}
document.querySelectorAll('[data-case]').forEach(btn=>btn.addEventListener('click',()=>loadCase(btn.dataset.case)));loadCase(new URLSearchParams(location.search).get('case')==='52'?'52':'29');
