const labels={
  'get_recent_measurements':['최근 계측','신고 전 계측값과 범위'],
  'get_signal_definitions':['센서 설명','각 센서가 어디서 무엇을 재는지'],
  'get_prior_incidents':['과거 신고','같은 설비의 이전 신고'],
  'get_maintenance_timeline':['정비 이력','이전 정비와 작업 기록'],
  'get_temporal_episodes':['벗어난 시간대','온도가 목표값(설정값)에서 벗어난 구간'],
  'query_measurement_window':['특정 시간대 조회','골라낸 구간을 다시 확인'],
  'finish_investigation':['조사 종료','충분하다고 판단하고 정리 시작']
};
const checkLabels={'C-room-impact':'실내·라디에이터 온도 확인','C-secondary-flow':'건물 배관 유량 측정','C-controls':'제어기 설정과 경보 이력 검토'};
const limitLabels={'L-no-room-evidence':'공급온도가 설정값과 맞아도 실내가 따뜻했다는 뜻은 아닙니다.','L-no-normal-range':'열 사용량과 유량이 평소 어느 정도여야 정상인지 데이터에 없습니다.','L-primary-flow':'도시 배관(1차) 유량으로는 건물 배관(2차)에 물이 얼마나 흐르는지 알 수 없습니다.'};
const checkDetails={'C-room-impact':'어느 방이 얼마나 추운지 실제 온도로 확인','C-secondary-flow':'건물 배관에 물이 충분히 흐르는지 재고 정상 범위와 비교','C-controls':'제어기 설정·경보·변경 기록을 시간순으로 확인'};
const rationaleKo={
  '29':{'C-room-impact':'14시 18분에 난방이 안 된다는 신고가 들어왔지만 공급온도는 63.9°C였습니다. 실제 실내·라디에이터 온도와 난방이 안 되는 범위를 확인해야 합니다.','C-secondary-flow':'공급온도는 설정값에 가깝지만 바깥 기온은 약 10°C입니다. 열이 충분히 전달되는지 보려면 건물 배관 유량을 측정해야 합니다.','C-controls':'공급온도와 설정값이 2°C 넘게 벌어진 구간이 여러 번 있었고, 최대 13.4°C까지 벌어졌습니다. 시간이 찍힌 제어기 설정과 변경 기록을 엔지니어와 함께 검토해야 합니다.'},
  '52':{'C-room-impact':'난방이 안 된다는 신고가 있었습니다. 공급온도는 설정값(63~68°C)을 잘 따라가지만 실내·라디에이터 온도는 측정되지 않아, 방까지 열이 전달됐는지 확인할 수 없습니다.','C-secondary-flow':'도시 배관(1차) 유량(1680~3960 l/h)만 기록돼 있고 건물 배관(2차) 유량은 측정되지 않아, 열을 충분히 보낼 수 있는지 판단할 수 없습니다.','C-controls':'24시간 동안 설정값이 63.0°C에서 68.6°C로 올랐습니다. 자동으로 바뀐 것인지 사람이 바꾼 것인지 제어기 설정·경보 기록을 엔지니어와 확인해야 합니다.'}
};
const signalKo={'s_hc1_supply_temperature':'공급온도','s_hc1_supply_temperature_setpoint':'설정값','p_net_meter_flow':'도시 배관(1차) 유량','outdoor_temperature':'바깥 기온'};
const statKo={first:'24시간 중 첫 값',last:'24시간 중 마지막 값',max:'24시간 중 최댓값',min:'24시간 중 최솟값'};
function factTitle(field){if(field==='problem')return '고객 신고';let m=field.match(/^temporal\.episode\.(\d+)$/);if(m)return `목표 온도에서 2°C 넘게 벗어난 구간 #${m[1]}`;if(field==='temporal.window_pair')return '특정 시각의 공급온도와 설정값';if(field==='temporal.paired_first')return '24시간 중 첫 시점의 공급온도와 설정값';if(field==='temporal.paired_last')return '24시간 중 마지막 시점의 공급온도와 설정값';m=field.match(/^signals\.(.+)\.(first|last|max|min)$/);if(m&&signalKo[m[1]])return `${signalKo[m[1]]} · ${statKo[m[2]]}`;return ''}
const state={case:'29',data:null,selected:0};
const $=sel=>document.querySelector(sel);
function el(name,cls,text){const node=document.createElement(name);if(cls)node.className=cls;if(text!==undefined)node.textContent=text;return node}
function displayValue(v){return typeof v==='object'?JSON.stringify(v,null,2):String(v??'—')}
function factNode(fact){const article=el('article','fact');article.id=`fact-${fact.id}`;const head=el('div','fact-head');head.append(el('code','',fact.id),el('span','',fact.unit||'공개 기록'));const title=factTitle(fact.source_field);article.append(head,el('p','fact-text',title||fact.text));if(title)article.append(el('p','fact-orig',fact.text));const dl=el('dl');[['기록 ID',fact.source_id],['필드',fact.source_field],['시간',fact.interval||'-'],['값',typeof fact.value==='object'?'위 설명 참고':displayValue(fact.value)]].forEach(([k,v])=>{dl.append(el('dt','',k),el('dd','',v))});article.append(dl);return article}
function render(){const d=state.data;const subtitle=state.case==='29'?'서브스테이션 17 · 개발 중 한 번도 보지 않은 설비':'서브스테이션 21 · 조사 종료 로직을 고친 뒤 다시 실행';$('#incident-title').textContent=`신고 #${state.case}`;$('#incident-subtitle').textContent=subtitle;$('#decision-time').textContent=d.decision_time;$('#case-meta').replaceChildren();const meta=$('#case-meta');[['결과',d.status==='reference_checked'?'근거 연결 확인됨':d.status],['모델','NVIDIA Nemotron 3 Ultra (NIM)'],['종료 방식',{explicit_finish_tool:'에이전트가 스스로 종료',planning_cap_handoff:'조회 한도 도달 후 정리'}[d.finish_reason]||d.finish_reason],['자료 조회',`${d.tool_calls.length}회`],['실행 시간',`${d.wall_seconds.toFixed(1)}초`]].forEach(([k,v])=>{const row=el('div','meta-row');row.append(el('span','',k),el('strong','',v));meta.append(row)});
  $('#check-list').replaceChildren();d.checks.forEach((check,i)=>{const btn=el('button','check-item');btn.type='button';btn.setAttribute('aria-pressed',String(state.selected===i));btn.append(el('span','check-no',String(i+1).padStart(2,'0')),el('span','check-title',checkLabels[check.id]||check.text),el('span','check-arrow','↗'));const detail=el('small','',checkDetails[check.id]||check.text);btn.querySelector('.check-title').append(detail);btn.addEventListener('click',()=>{state.selected=i;renderChecks();if(window.matchMedia('(max-width: 950px)').matches){const heading=$('#inspector-title');heading.setAttribute('tabindex','-1');heading.focus({preventScroll:true});heading.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'})}});$('#check-list').append(btn)});renderChecks();
  $('#tool-list').replaceChildren();d.tool_calls.forEach((tool,i)=>{const row=el('div','tool-item');row.append(el('span','tool-no',String(i+1).padStart(2,'0')));const body=el('div');body.append(el('strong','',labels[tool.name]?.[0]||tool.name),el('p','',labels[tool.name]?.[1]||''));if(Object.keys(tool.arguments).length)body.append(el('code','',tool.arguments.start&&tool.arguments.end?`${tool.arguments.start} ~ ${tool.arguments.end}`:Object.entries(tool.arguments).map(([k,v])=>`${k}: ${v}`).join(' / ')));row.append(body);$('#tool-list').append(row)});
  $('#limits').replaceChildren();d.limits.forEach(item=>$('#limits').append(el('li','',limitLabels[item.id]||item.text)));const review=$('#postrun-review-summary');review.hidden=!d.postrun_review;review.textContent=d.postrun_review?'실행 후 별도 검토에서 유량 점검 이유 일부가 인용한 기록과 맞지 않는다는 지적이 나왔습니다. 모델 출력은 고치지 않고 그대로 두었습니다. 유량 점검 항목을 누르면 자세히 볼 수 있습니다.':'';const warn=$('#review-warning');warn.hidden=!d.budget_exhausted;warn.textContent=d.budget_exhausted?'이 실행은 에이전트가 스스로 조사를 끝낸 것이 아니라, 조회 6회 한도에 도달해 정리 단계로 넘어간 결과입니다.':'';$('#download-json').href=`assets/system2-${state.case}.json`;document.querySelectorAll('[data-case]').forEach(btn=>btn.setAttribute('aria-pressed',String(btn.dataset.case===state.case)))}
function renderChecks(){const d=state.data,check=d.checks[state.selected];document.querySelectorAll('.check-item').forEach((btn,i)=>btn.setAttribute('aria-pressed',String(i===state.selected)));$('#inspector-title').textContent=checkLabels[check.id]||check.text;const ko=rationaleKo[state.case]?.[check.id];const sum=$('#inspector-summary');sum.textContent=ko||check.rationale;if(ko)sum.append(el('span','orig',check.rationale));const postrun=$('#postrun-check-review');const issues=d.postrun_review?.by_check?.[check.id]||[];postrun.hidden=issues.length===0;postrun.replaceChildren();if(issues.length){postrun.append(el('strong','','실행 후 검토 의견'));issues.forEach(issue=>postrun.append(el('p','',issue)));postrun.append(el('small','','AI 검토 의견이며 현장 전문가 판단은 아닙니다.'))}$('#fact-count').textContent=`근거 ${check.fact_ids.length}건`;const wrap=$('#facts');wrap.replaceChildren();check.fact_ids.forEach(id=>{const fact=d.facts[id];if(fact)wrap.append(factNode(fact))});}
async function loadCase(caseId){state.case=caseId;state.selected=0;try{const response=await fetch(`assets/system2-${caseId}.json`);if(!response.ok)throw new Error(`HTTP ${response.status}`);state.data=await response.json();render();history.replaceState(null,'',`${location.pathname}?case=${caseId}`)}catch(error){$('#check-list').textContent='공개 실행 데이터를 읽지 못했습니다. 정적 웹 서버로 이 페이지를 열어 주세요.';$('#inspector-summary').textContent=String(error)}}
document.querySelectorAll('[data-case]').forEach(btn=>btn.addEventListener('click',()=>loadCase(btn.dataset.case)));loadCase(new URLSearchParams(location.search).get('case')==='52'?'52':'29');
